server {
    listen 10000 default_server;
    listen [::]:10000 default_server;
    server_name _;

    root /var/www/vue3-todo-list;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
