server {
    listen 80;
    listen [::]:80;
    server_name todo.loliowo.com;

    root /var/www/vue3-todo-list;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
